services:
  onesec:
    build:
      context: ./server
    command: "node index.mjs 1000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:1337/noop"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
  fivesec:
    build:
      context: ./server
    command: "node index.mjs 5000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:1337/noop"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
  tensec:
    build:
      context: ./server
    command: "node index.mjs 10000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:1337/noop"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
  loadbalancer:
    build: ./load-balancer
    volumes:
      - type: bind
        source: ./load-balancer/logs
        target: /var/log/nginx/logs
    tty: true
    depends_on:
      onesec:
        condition: service_healthy
      fivesec:
        condition: service_healthy
      tensec:
        condition: service_healthy
    ports:
      - '8080:8080'
