events {  worker_connections 1024; }

http {
  upstream backends {
    server onesec:1337;
    server fivesec:1337;
    server tensec:1337;
    keepalive 32;
  }
  server {
    listen 8080;
    server_name localhost;
    location / {
       proxy_pass http://backends;
       proxy_set_header Host $host;
       proxy_read_timeout 30s;
       proxy_http_version 1.1;
       proxy_set_header Connection "";
    }
  }
    log_format main_ext '[$time_local] $request -$upstream_addr returned $status in $request_time seconds';

    access_log /var/log/nginx/logs/access.log main_ext;
}
